name: Deployment
on:
  push:
    branches:
      - main
jobs:
  sync:
    name: Yeet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@v0.0.34
        with:
            app_id: "65678405726638080"
            server: https://api.edgeserver.io
            token: ${{ secrets.SIGNAL_TOKEN }}
            directory: ./